### ISSUE TITLE
Unable to install with angular 1.4.8

### ISSUE THREAD

**Issue by dksfcb** [rosslavery/velocity-ui-angular#8]
bower velocity-ui-angular#*     cached git://github.com/rosslavery/velocity-ui-angular.git#0.4.0
bower velocity-ui-angular#*   validate 0.4.0 against git://github.com/rosslavery/velocity-ui-angular.git#*
bower velocity#~0.11.6          cached git://github.com/julianshapiro/velocity.git#0.11.9
bower velocity#~0.11.6        validate 0.11.9 against git://github.com/julianshapiro/velocity.git#~0.11.6
bower angular-animate#~1.2.15   cached git://github.com/angular/bower-angular-animate.git#1.2.29
bower angular-animate#~1.2.15 validate 1.2.29 against git://github.com/angular/bower-angular-animate.git#~1.2.15
bower angular#~1.2.15           cached git://github.com/angular/bower-angular.git#1.2.29
bower angular#~1.2.15         validate 1.2.29 against git://github.com/angular/bower-angular.git#~1.2.15
bower angular#>=1.3.0           cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.3.0         validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.3.0
bower angular#>= 1.0.8          cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.0.8        validate 1.4.8 against git://github.com/angular/bower-angular.git#>= 1.0.8
bower angular#>= 1.2.23         cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.2.23       validate 1.4.8 against git://github.com/angular/bower-angular.git#>= 1.2.23
bower                        ECONFLICT Unable to find suitable version for velocity

**Comment by rosslavery** [comment]
Should be fixed now, thanks a bunch for the PR.
